# deploy/03-rbac.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-manager-sa
  namespace: scadable-faas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faas-manager-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: faas-manager-binding
subjects:
  - kind: ServiceAccount
    name: faas-manager-sa
    namespace: scadable-faas
roleRef:
  kind: ClusterRole
  name: faas-manager-role
  apiGroup: rbac.authorization.k8s.io